#!/bin/bash

OS="$(uname)"

if [ "$OS" == "Darwin" ]; then
    echo "Liste des interfaces réseau sur macOS :"
    networksetup -listallhardwareports | grep "Device" | awk '{print $2}'
elif [ "$OS" == "Linux" ]; then
    echo "Liste des interfaces réseau sur Linux :"
    ip -o link show | awk -F': ' '{print $2}'
else
    echo "Système d'exploitation non pris en charge."
    exit 1
fi
